# fly.toml app configuration file generated for profane on 2023-11-13T18:39:12+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "profane"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
